### ISSUE TITLE
All list items inside an OrderedList use the same counter - also nested list items

### ISSUE THREAD

**Issue by bertspaan** [Amsterdam/amsterdam-styled-components#215]
When using `<OrderedList>` and `<ListItem>` from `'@datapunt/asc-ui'`, __all__ `<li>`s inside the first `<OrderedList>` are using the same counter. Also nested `<li>`s. This will lead to HTML like this:

```
1. Item
2. Item
    3. Nested item
    4. Nested item
5. Item
```

This is (some of) the CSS introduced by `<OrderedList>` and `<ListItem>`:

```css
.hpwGRC {
  margin: 0 0 24px 24px;
  padding: 0;
  counter-reset: item;
}

.hpwGRC li {
  position: relative;
  color: #000000;
  font-weight: 400;
  font-size: 16px;
  -webkit-letter-spacing: inherit;
  -moz-letter-spacing: inherit;
  -ms-letter-spacing: inherit;
  letter-spacing: inherit;
  line-height: 22px;
  margin-bottom: 8;
  list-style-type: none;
  counter-increment: item;
}

.hpwGRC li::before {
  display: inline-block;
  width: 1em;
  position: absolute;
  left: -24px;
  top: 0;
  padding-right: 0.5em;
  font-weight: bold;
  text-align: right;
  content: counter(item) '.';
}
```
